# This playbook uses the win_ping module to test connectivity to Windows hosts
- name: Ping
  hosts: all
  become: false

  tasks:
  - name: ping
    win_ping:

  - name: debug
    debug:
      msg: "This is a debug message"
